# 01. Data Sourcing - Pandas

## 01.1. Importação das bibliotecas

### 01.1.1. Importando as bibliotecas nativas do Python

In [1]:
import os
import sys

### 01.1.2. Importando as bibliotecas de terceiros

In [2]:
import pandas as pd

### 01.1.3. Importando os módulos locais do projeto

In [3]:
sys.path.append('..')
import params.consts as consts

## 01.2. Fontes dos dados

**Como os datasets são bem grandes, o arquivo de cada mês contém cerca de 120MB de tamanho e como são 25 meses (abr/2018 a mai/2020) dão cerca de 2,5GB de espaço. Além disso, no arquivo compactado baixado do Kaggle tem o arquivo total com mais 2,5GB, dando no total um arquivo com cerca de 5GB de dados. O arquivo compactado do Kaggle tem cerca de 1GB de tamanho. Por isso, ao subir o projeto para o GitHub desabilitei a pasta data pois subiria muitos arquivos brutos bem pesados, fora os tratados que ainda assim seria pesados também. E para não deixar isso ocupando espaço no meu computador optei por excluir esses datasets, deixando apenas o "dataset_preview" para entender os dados quando precisasse. Para rodar novamente esse projeto, acesse o site desse projeto no Kaggle em "https://www.kaggle.com/datasets/allanbruno/airbnb-rio-de-janeiro", baixe novamente esses arquivos com os dados brutos e coloque na pasta "data/01_resource" para que possa funcionar normalmente**

### 01.2.1. Listando as fontes dos dados

|Fonte de Dados       |Local           |Arquivos                   |Tabela|Descrição                                                 |Formato|Qtd|
|---------------------|----------------|---------------------------|------|----------------------------------------------------------|-------|---|
|Data Lakes           |                |-                          |-     |                                                         |-      |-  |
|Data Warehouses      |                |-                          |-     |                                                         |-      |-  |
|Clouds               |                |-                          |-     |                                                         |-      |-  |
|Bancos de Dados SQL  |                |-                          |-     |                                                         |-      |-  |
|Bancos de Dados NoSQL|                |-                          |-     |                                                         |-      |-  |
|APIs                 |                |-                          |-     |                                                         |-      |-  |
|ERPs                 |                |-                          |-     |                                                         |-      |-  |
|CRMs                 |                |-                          |-     |                                                         |-      |-  |
|Web Scraping         |                |-                          |-     |                                                         |-      |-  |
|Sistemas Empresariais|data/01_resource|25 arquivos padrão "mêsano"|Fato  |Tabelas de anúncios de imóveis de abr/2018 a mai/2020|Csv    |25 |
|Dados Locais         |                |-                          |-     |                                                         |-      |-  |
|Outros               |                |-                          |-     |                                                         |-      |-  |

## 01.3. União entre tabelas

### 01.3.1. Habilitando a exibição de todas as colunas e linhas

In [4]:
pd.set_option('display.max_columns', None); pd.set_option('display.max_rows', None)

### 01.3.2. Entendendo uma das tabelas e seus tipos de dados

In [5]:
df_04_2018 = pd.read_csv('../data/01_resource/abril2018.csv', low_memory = False)

In [6]:
df_04_2018.head(5)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,14063,https://www.airbnb.com/rooms/14063,20180414160018,2018-04-14,Living in a Postcard,"Besides the most iconic's view, our apartment ...",NaN,"Besides the most iconic's view, our apartment ...",none,Best and favorite neighborhood of Rio. Perfect...,NaN,Everything is there. METRO is 5 min walk. Dir...,NaN,NaN,strictly no smoking in the apartment ! We want...,NaN,NaN,https://a0.muscache.com/im/pictures/66421/ae9b...,NaN,53598,https://www.airbnb.com/users/show/53598,Shalev,2009-11-12,FL,"Hello , my name is Shalev , I am an orchestra ...",NaN,NaN,NaN,f,https://a0.muscache.com/im/users/53598/profile...,https://a0.muscache.com/im/users/53598/profile...,Botafogo,1.0,1.0,"['email', 'phone', 'reviews', 'jumio']",t,t,"Rio de Janeiro, RJ, Brazil",Botafogo,Botafogo,NaN,Rio de Janeiro,RJ,22250-040,Rio De Janeiro,"Rio de Janeiro, Brazil",BR,Brazil,-22.946854,-43.182737,t,Apartment,Entire home/apt,4,1.0,0.0,2.0,Real Bed,"{TV,Internet,""Air conditioning"",Kitchen,Doorma...",NaN,$133.00,$823.00,"$2,698.00","$1,025.00",$102.00,2,$34.00,60,365,7 weeks ago,t,28,58,88,363,2018-04-14,38,2010-01-03,2018-03-04,91.0,9.0,9.0,9.0,9.0,9.0,9.0,f,NaN,NaN,f,f,strict_14_with_grace_period,f,f,1,0.38
1,17878,https://www.airbnb.com/rooms/17878,20180414160018,2018-04-14,Very Nice 2Br - Copacabana - WiFi,Please note that special rates apply for New Y...,- large balcony which looks out on pedestrian ...,Please note that special rates apply for New Y...,none,This is the best spot in Rio. Everything happe...,NaN,Excellent location. Close to all major public ...,The entire apartment is yours. It is a vacatio...,I will be available throughout your stay shoul...,Please leave the apartment in a clean fashion ...,NaN,NaN,https://a0.muscache.com/im/pictures/65320518/3...,NaN,68997,https://www.airbnb.com/users/show/68997,Matthias,2010-01-08,"Rio de Janeiro, Rio de Janeiro, Brazil",I used to work as a journalist all around the ...,within an hour,100%,NaN,t,https://a0.muscache.com/im/pictures/67b13cea-8...,https://a0.muscache.com/im/pictures/67b13cea-8...,Copacabana,2.0,2.0,"['email', 'phone', 'reviews']",t,f,"Rio de Janeiro, Rio de Janeiro, Brazil",Copacabana,Copacabana,NaN,Rio de Janeiro,Rio de Janeiro,22020-050,Rio De Janeiro,"Rio de Janeiro, Brazil",BR,Brazil,-22.965919,-43.178962,t,Condominium,Entire home/apt,5,1.0,2.0,2.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$270.00,NaN,NaN,$0.00,$273.00,2,$51.00,4,90,yesterday,t,11,29,58,286,2018-04-14,205,2010-07-15,2018-04-10,93.0,10.0,9.0,10.0,10.0,9.0,9.0,f,NaN,NaN,t,f,strict,f,f,1,2.17
2,24480,https://www.airbnb.com/rooms/24480,20180414160018,2018-04-14,Nice and cozy near Ipanema Beach,My studio is located in the best of Ipanema. ...,The studio is located at Vinicius de Moraes St...,My studio is located in the best of Ipanema. ...,none,"The beach, the lagoon, Ipanema is a great loca...","O prédio é bastante simples , mas o apartament...",NaN,"From the International airport, take a regula...",Os hóspedes podem perguntar por email suas que...,Please remove sand when you come from the beac...,NaN,NaN,https://a0.muscache.com/im/pictures/11955612/b...,NaN,99249,https://www.airbnb.com/users/show/99249,Goya,2010-03-26,"Rio de Janeiro, Rio de Janeiro, Brazil",Welcome to Rio!\r\nI am a filmmaker and a tea...,within an hour,100%,NaN,f,https://a0.muscache.com/im/pictures/6b40475c-2...,https://a0.muscache.com/im/pictures/6b40475c-2...,Ipanema,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Rio de Janeiro, Rio de Janeiro, Brazil",Ipanema,Ipanema,NaN,Rio de Janeiro,Rio de Janeiro,22411-010,Rio De Janeiro,"Rio de Janeiro, Brazil",BR,Brazil,-22.985698,-43.201935,t,Apartment,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Wifi,""Air conditioning"",""First ...",NaN,$222.00,NaN,NaN,$851.00,$211.00,2,$215.00,3,90,5 weeks ago,t,0,0,0,0,2018-04-14,85,2010-09-26,2018-02-14,95.0,10.0,10.0,10.0,10.0,10.0,9.0,f,NaN,NaN,f,f,strict,f,f,1,0.92
3,25026,https://www.airbnb.com/rooms/25026,20180414160018,2018-04-14,Beautiful Modern Decorated Studio in Copa,"Our apartment is a little gem, everyone loves ...",This newly renovated studio (last renovations ...,"Our apartment is a little gem, everyone loves ...",none,Copacabana is a lively neighborhood and the ap...,"For any stay superior to 15 days, an additiona...",At night we recommend you to take taxis only. ...,"internet wi-fi, cable tv, air cond, ceiling fa...","Only at check in, we like to leave our guests ...",Smoking outside only. Family building so pleas...,NaN,NaN,https://a0.muscache.com/im/pictures/3003965/68...,NaN,102840,https://www.airbnb.com/users/show/102840,Viviane,2010-04-03,"Rio de Janeiro, State of Rio de Janeiro, Brazil","Hi guys, We're a lovely team of 3 people:\r\n\...",within an hour,100%,NaN,f,https://a0.muscache.com/im/pictures/9e204f80-1...,https://a0.muscache.com/im/pictures/9e204f80-1...,Copacabana,3.0,3.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Rio de Janeiro, Rio de Janeiro, Brazil",Copacabana,Copacabana,NaN,Rio de Janeiro,Rio de Janeiro,22060-020,Rio De Janeiro,"Rio de Janeiro, Brazil",BR,Brazil,-22.977117,-43.190454,t,Apartment,Entire home/apt,3,1.0,1.0,2.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$161.00,NaN,NaN,"$1,000.00",$220.00,2,$45.00,4,30,today,t,28,58,88,363,2018-04-14,208,2010-06-07,2018-03-28,94.0,9.0,10.0,10.0,10.0,10.0,9.0,f,NaN,NaN,f,f,strict,t,t,3,2.17
4,31560,https://www.airbnb.com/rooms/31560,20180414160018,2018-04-14,NICE & COZY 1BDR - IPANEMA BEACH,This nice and clean 1 bedroom apartment is loc...,This nice and clean 1 bedroom apartment is loc...,This nice and clean 1 bedroom apartment is loc...,none,Die Nachbarschaft von Ipanema ist super lebend...,NaN,"Bus, U-Bahn, Taxi und Leihfahrräder in der Nähe.","Die Urlauber dürfen das Badezimmer benutzen, d...",NaN,"So far, I haven't had any problems with guests...",NaN,NaN,https://a0.muscache.com/im/pictures/83114449/2...,NaN,135635,https://www.airbnb.com/users/show/135635,Renata,2010-05-31,"Rio de Janeiro, Rio de Janeiro, Brazil",I was born and raised in Rio de (Website hidde...,within an hour,100%,NaN,t,https://a0.muscache.com/im/users/135635/profil...,https://a0.muscache.com/im/users/135635/profil...,Ipanema,1.0,1.0,"['email', 'phone', 'manual_online', 'facebook'...",t,t,"Rio de Janeiro, RJ, Brazil",Ipanema,Ipanema,NaN,Rio de Janeiro,RJ,22410-003,Rio De Janeiro,"Rio de Janeiro, Brazil",BR,Brazil,-22.983024,-43.214270,t,Apartment,Entire home/apt,3,1.0,1.0,2.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$222.00,NaN,NaN,NaN,$85.00,2,$68.00,2,1125,5 weeks ago,t,15,45,75,345,2018-04-14,200,2010-07-11,2018-04-01,96.0,10.0,10.0,10.0,10.0,10.0,9.0,f,NaN,NaN,t,f,strict,f,f,1,2.12

In [7]:
df_04_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39743 entries, 0 to 39742
Data columns (total 96 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                39743 non-null  int64
 1   listing_url                       39743 non-null  object
 2   scrape_id                         39743 non-null  int64
 3   last_scraped                      39743 non-null  object
 4   name                              39665 non-null  object
 5   summary                           38974 non-null  object
 6   space                             23205 non-null  object
 7   description                       39675 non-null  object
 8   experiences_offered               39743 non-null  object
 9   neighborhood_overview             19791 non-null  object
 10  notes                             11503 non-null  object
 11  transit                           19546 non-null  object
 12  access                            18739 non-null  object
 13  interaction                       17706 non-null  object
 14  house_rules                       19557 non-null  object
 15  thumbnail_url                     0 non-null      float64
 16  medium_url                        0 non-null      float64
 17  picture_url                       39743 non-null  object
 18  xl_picture_url                    0 non-null      float64
 19  host_id                           39743 non-null  int64
 20  host_url                          39743 non-null  object
 21  host_name                         39712 non-null  object
 22  host_since                        39712 non-null  object
 23  host_location                     39486 non-null  object
 24  host_about                        19428 non-null  object
 25  host_response_time                22008 non-null  object
 26  host_response_rate                22008 non-null  object
 27  host_acceptance_rate              0 non-null      float64
 28  host_is_superhost                 39712 non-null  object
 29  host_thumbnail_url                39712 non-null  object
 30  host_picture_url                  39712 non-null  object
 31  host_neighbourhood                23423 non-null  object
 32  host_listings_count               39712 non-null  float64
 33  host_total_listings_count         39712 non-null  float64
 34  host_verifications                39712 non-null  object
 35  host_has_profile_pic              39712 non-null  object
 36  host_identity_verified            39712 non-null  object
 37  street                            39743 non-null  object
 38  neighbourhood                     37726 non-null  object
 39  neighbourhood_cleansed            39743 non-null  object
 40  neighbourhood_group_cleansed      0 non-null      float64
 41  city                              39723 non-null  object
 42  state                             39689 non-null  object
 43  zipcode                           37428 non-null  object
 44  market                            39686 non-null  object
 45  smart_location                    39743 non-null  object
 46  country_code                      39743 non-null  object
 47  country                           39743 non-null  object
 48  latitude                          39743 non-null  float64
 49  longitude                         39743 non-null  float64
 50  is_location_exact                 39743 non-null  object
 51  property_type                     39743 non-null  object
 52  room_type                         39743 non-null  object
 53  accommodates                      39743 non-null  int64
 54  bathrooms                         39663 non-null  float64
 55  bedrooms                          39719 non-null  float64
 56  beds                              39686 non-null  float64
 57  bed_type                          39743 non-null  object
 58  amenities                         39743 non-null  object
 59  square_feet                       692 non-null    float64
 60  price                             39743 non-null  object
 61  weekly_price                      3970 non-null   object
 62  monthly_price                     4304 non-null   object
 63  security_deposit                  19432 non-null  object
 64  cleaning_fee                      24876 non-null  object
 65  guests_included                   39743 non-null  int64
 66  extra_people                      39743 non-null  object
 67  minimum_nights                    39743 non-null  int64
 68  maximum_nights                    39743 non-null  int64
 69  calendar_updated                  39743 non-null  object
 70  has_availability                  39743 non-null  object
 71  availability_30                   39743 non-null  int64
 72  availability_60                   39743 non-null  int64
 73  availability_90                   39743 non-null  int64
 74  availability_365                  39743 non-null  int64
 75  calendar_last_scraped             39743 non-null  object
 76  number_of_reviews                 39743 non-null  int64
 77  first_review                      19466 non-null  object
 78  last_review                       19484 non-null  object
 79  review_scores_rating              18598 non-null  float64
 80  review_scores_accuracy            18563 non-null  float64
 81  review_scores_cleanliness         18574 non-null  float64
 82  review_scores_checkin             18556 non-null  float64
 83  review_scores_communication       18568 non-null  float64
 84  review_scores_location            18559 non-null  float64
 85  review_scores_value               18557 non-null  float64
 86  requires_license                  39743 non-null  object
 87  license                           1 non-null      object
 88  jurisdiction_names                0 non-null      float64
 89  instant_bookable                  39743 non-null  object
 90  is_business_travel_ready          39743 non-null  object
 91  cancellation_policy               39743 non-null  object
 92  require_guest_profile_picture     39743 non-null  object
 93  require_guest_phone_verification  39743 non-null  object
 94  calculated_host_listings_count    39743 non-null  int64
 95  reviews_per_month                 19466 non-null  float64
dtypes: float64(22), int64(13), object(61)
memory usage: 29.1+ MB

### 01.3.3. Unindo as tabelas

In [8]:
dfs = []

meses = {'jan': 1, 'fev': 2, 'mar': 3, 'abr': 4, 'mai': 5, 'jun': 6, 'jul': 7, 'ago': 8, 'set': 9, 'out': 10, 'nov': 11, 'dez': 12}

data_folder = '../data/01_resource'

for i in os.listdir(data_folder):

    if i.endswith('.csv'):
        
        nome_mes = i[:3]
        if nome_mes not in meses: continue
        mes = meses[nome_mes]

        ano = i[-8:]
        ano = int(ano.replace('.csv', ''))
        
        arquivo_nome = os.path.join(data_folder, i)
        
        df = pd.read_csv(arquivo_nome, low_memory = False)

        df['ano'] = ano
        df['mes'] = mes

        dfs.append(df)

dataset_raw = pd.concat(dfs, ignore_index = True)

In [9]:
dataset_raw.head(5)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month,ano,mes,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,number_of_reviews_ltm,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,14063,https://www.airbnb.com/rooms/14063,20180414160018,2018-04-14,Living in a Postcard,"Besides the most iconic's view, our apartment ...",NaN,"Besides the most iconic's view, our apartment ...",none,Best and favorite neighborhood of Rio. Perfect...,NaN,Everything is there. METRO is 5 min walk. Dir...,NaN,NaN,strictly no smoking in the apartment ! We want...,NaN,NaN,https://a0.muscache.com/im/pictures/66421/ae9b...,NaN,53598,https://www.airbnb.com/users/show/53598,Shalev,2009-11-12,FL,"Hello , my name is Shalev , I am an orchestra ...",NaN,NaN,NaN,f,https://a0.muscache.com/im/users/53598/profile...,https://a0.muscache.com/im/users/53598/profile...,Botafogo,1.0,1.0,"['email', 'phone', 'reviews', 'jumio']",t,t,"Rio de Janeiro, RJ, Brazil",Botafogo,Botafogo,NaN,Rio de Janeiro,RJ,22250-040,Rio De Janeiro,"Rio de Janeiro, Brazil",BR,Brazil,-22.946854,-43.182737,t,Apartment,Entire home/apt,4,1.0,0.0,2.0,Real Bed,"{TV,Internet,""Air conditioning"",Kitchen,Doorma...",NaN,$133.00,$823.00,"$2,698.00","$1,025.00",$102.00,2,$34.00,60,365,7 weeks ago,t,28,58,88,363,2018-04-14,38,2010-01-03,2018-03-04,91.0,9.0,9.0,9.0,9.0,9.0,9.0,f,NaN,NaN,f,f,strict_14_with_grace_period,f,f,1,0.38,2018,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17878,https://www.airbnb.com/rooms/17878,20180414160018,2018-04-14,Very Nice 2Br - Copacabana - WiFi,Please note that special rates apply for New Y...,- large balcony which looks out on pedestrian ...,Please note that special rates apply for New Y...,none,This is the best spot in Rio. Everything happe...,NaN,Excellent location. Close to all major public ...,The entire apartment is yours. It is a vacatio...,I will be available throughout your stay shoul...,Please leave the apartment in a clean fashion ...,NaN,NaN,https://a0.muscache.com/im/pictures/65320518/3...,NaN,68997,https://www.airbnb.com/users/show/68997,Matthias,2010-01-08,"Rio de Janeiro, Rio de Janeiro, Brazil",I used to work as a journalist all around the ...,within an hour,100%,NaN,t,https://a0.muscache.com/im/pictures/67b13cea-8...,https://a0.muscache.com/im/pictures/67b13cea-8...,Copacabana,2.0,2.0,"['email', 'phone', 'reviews']",t,f,"Rio de Janeiro, Rio de Janeiro, Brazil",Copacabana,Copacabana,NaN,Rio de Janeiro,Rio de Janeiro,22020-050,Rio De Janeiro,"Rio de Janeiro, Brazil",BR,Brazil,-22.965919,-43.178962,t,Condominium,Entire home/apt,5,1.0,2.0,2.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$270.00,NaN,NaN,$0.00,$273.00,2,$51.00,4,90,yesterday,t,11,29,58,286,2018-04-14,205,2010-07-15,2018-04-10,93.0,10.0,9.0,10.0,10.0,9.0,9.0,f,NaN,NaN,t,f,strict,f,f,1,2.17,2018,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,24480,https://www.airbnb.com/rooms/24480,20180414160018,2018-04-14,Nice and cozy near Ipanema Beach,My studio is located in the best of Ipanema. ...,The studio is located at Vinicius de Moraes St...,My studio is located in the best of Ipanema. ...,none,"The beach, the lagoon, Ipanema is a great loca...","O prédio é bastante simples , mas o apartament...",NaN,"From the International airport, take a regula...",Os hóspedes podem perguntar por email suas que...,Please remove sand when you come from the beac...,NaN,NaN,https://a0.muscache.com/im/pictures/11955612/b...,NaN,99249,https://www.airbnb.com/users/show/99249,Goya,2010-03-26,"Rio de Janeiro, Rio de Janeiro, Brazil",Welcome to Rio!\r\nI am a filmmaker and a tea...,within an hour,100%,NaN,f,https://a0.muscache.com/im/pictures/6b40475c-2...,https://a0.muscache.com/im/pictures/6b40475c-2...,Ipanema,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Rio de Janeiro, Rio de Janeiro, Brazil",Ipanema,Ipanema,NaN,Rio de Janeiro,Rio de Janeiro,22411-010,Rio De Janeiro,"Rio de Janeiro, Brazil",BR,Brazil,-22.985698,-43.201935,t,Apartment,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Wifi,""Air conditioning"",""First ...",NaN,$222.00,NaN,NaN,$851.00,$211.00,2,$215.00,3,90,5 weeks ago,t,0,0,0,0,2018-04-14,85,2010-09-26,2018-02-14,95.0,10.0,10.0,10.0,10.0,10.0,9.0,f,NaN,NaN,f,f,strict,f,f,1,0.92,2018,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25026,https://www.airbnb.com/rooms/25026,20180414160018,2018-04-14,Beautiful Modern Decorated Studio in Copa,"Our apartment is a little gem, everyone loves ...",This newly renovated studio (last renovations ...,"Our apartment is a little gem, everyone loves ...",none,Copacabana is a lively neighborhood and the ap...,"For any stay superior to 15 days, an additiona...",At night we recommend you to take taxis only. ...,"internet wi-fi, cable tv, air cond, ceiling fa...","Only at check in, we like to leave our guests ...",Smoking outside only. Family building so pleas...,NaN,NaN,https://a0.muscache.com/im/pictures/3003965/68...,NaN,102840,https://www.airbnb.com/users/show/102840,Viviane,2010-04-03,"Rio de Janeiro, State of Rio de Janeiro, Brazil","Hi guys, We're a lovely team of 3 people:\r\n\...",within an hour,100%,NaN,f,https://a0.muscache.com/im/pictures/9e204f80-1...,https://a0.muscache.com/im/pictures/9e204f80-1...,Copacabana,3.0,3.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Rio de Janeiro, Rio de Janeiro, Brazil",Copacabana,Copacabana,NaN,Rio de Janeiro,Rio de Janeiro,22060-020,Rio De Janeiro,"Rio de Janeiro, Brazil",BR,Brazil,-22.977117,-43.190454,t,Apartment,Entire home/apt,3,1.0,1.0,2.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$161.00,NaN,NaN,"$1,000.00",$220.00,2,$45.00,4,30,today,t,28,58,88,363,2018-04-14,208,2010-06-07,2018-03-28,94.0,9.0,10.0,10.0,10.0,10.0,9.0,f,NaN,NaN,f,f,strict,t,t,3,2.17,2018,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,31560,https://www.airbnb.com/rooms/31560,20180414160018,2018-04-14,NICE & COZY 1BDR - IPANEMA BEACH,This nice and clean 1 bedroom apartment is loc...,This nice and clean 1 bedroom apartment is loc...,This nice and clean 1 bedroom apartment is loc...,none,Die Nachbarschaft von Ipanema ist super lebend...,NaN,"Bus, U-Bahn, Taxi und Leihfahrräder in der Nähe.","Die Urlauber dürfen das Badezimmer benutzen, d...",NaN,"So far, I haven't had any problems with guests...",NaN,NaN,https://a0.muscache.com/im/pictures/83114449/2...,NaN,135635,https://www.airbnb.com/users/show/135635,Renata,2010-05-31,"Rio de Janeiro, Rio de Janeiro, Brazil",I was born and raised in Rio de (Website hidde...,within an hour,100%,NaN,t,https://a0.muscache.com/im/users/135635/profil...,https://a0.muscache.com/im/users/135635/profil...,Ipanema,1.0,1.0,"['email', 'phone', 'manual_online', 'facebook'...",t,t,"Rio de Janeiro, RJ, Brazil",Ipanema,Ipanema,NaN,Rio de Janeiro,RJ,22410-003,Rio De Janeiro,"Rio de Janeiro, Brazil",BR,Brazil,-22.983024,-43.214270,t,Apartment,Entire home/apt,3,1.0,1.0,2.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$222.00,NaN,NaN,NaN,$85.00,2,$68.00,2,1125,5 weeks ago,t,15,45,75,345,2018-04-14,200,2010-07-11,2018-04-01,96.0,10.0,10.0,10.0,10.0,10.0,9.0,f,NaN,NaN,t,f,strict,f,f,1,2.12,2018,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
dataset_raw.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 902210 entries, 0 to 902209
Data columns (total 108 columns):
 #    Column                                        Non-Null Count   Dtype
---   ------                                        --------------   -----
 0    id                                            902210 non-null  int64
 1    listing_url                                   902210 non-null  object
 2    scrape_id                                     902210 non-null  int64
 3    last_scraped                                  902210 non-null  object
 4    name                                          900538 non-null  object
 5    summary                                       860406 non-null  object
 6    space                                         543496 non-null  object
 7    description                                   884040 non-null  object
 8    experiences_offered                           902210 non-null  object
 9    neighborhood_overview                         481672 non-null  object
 10   notes                                         284885 non-null  object
 11   transit                                       476428 non-null  object
 12   access                                        428360 non-null  object
 13   interaction                                   429883 non-null  object
 14   house_rules                                   457813 non-null  object
 15   thumbnail_url                                 0 non-null       float64
 16   medium_url                                    0 non-null       float64
 17   picture_url                                   902210 non-null  object
 18   xl_picture_url                                0 non-null       float64
 19   host_id                                       902210 non-null  int64
 20   host_url                                      902210 non-null  object
 21   host_name                                     901750 non-null  object
 22   host_since                                    901750 non-null  object
 23   host_location                                 897235 non-null  object
 24   host_about                                    433413 non-null  object
 25   host_response_time                            500367 non-null  object
 26   host_response_rate                            500364 non-null  object
 27   host_acceptance_rate                          94742 non-null   object
 28   host_is_superhost                             901750 non-null  object
 29   host_thumbnail_url                            901750 non-null  object
 30   host_picture_url                              901750 non-null  object
 31   host_neighbourhood                            555598 non-null  object
 32   host_listings_count                           901750 non-null  float64
 33   host_total_listings_count                     901750 non-null  float64
 34   host_verifications                            901750 non-null  object
 35   host_has_profile_pic                          901750 non-null  object
 36   host_identity_verified                        901750 non-null  object
 37   street                                        902210 non-null  object
 38   neighbourhood                                 844133 non-null  object
 39   neighbourhood_cleansed                        902210 non-null  object
 40   neighbourhood_group_cleansed                  0 non-null       float64
 41   city                                          900606 non-null  object
 42   state                                         900922 non-null  object
 43   zipcode                                       854654 non-null  object
 44   market                                        900956 non-null  object
 45   smart_location                                902210 non-null  object
 46   country_code                                  902210 non-null  object
 47   country                                       902210 non-null  object
 48   latitude                                      902210 non-null  float64
 49   longitude                                     902210 non-null  float64
 50   is_location_exact                             902210 non-null  object
 51   property_type                                 902210 non-null  object
 52   room_type                                     902210 non-null  object
 53   accommodates                                  902210 non-null  int64
 54   bathrooms                                     900486 non-null  float64
 55   bedrooms                                      901360 non-null  float64
 56   beds                                          899708 non-null  float64
 57   bed_type                                      902210 non-null  object
 58   amenities                                     902210 non-null  object
 59   square_feet                                   14048 non-null   float64
 60   price                                         902210 non-null  object
 61   weekly_price                                  75832 non-null   object
 62   monthly_price                                 83302 non-null   object
 63   security_deposit                              480930 non-null  object
 64   cleaning_fee                                  588704 non-null  object
 65   guests_included                               902210 non-null  int64
 66   extra_people                                  902210 non-null  object
 67   minimum_nights                                902210 non-null  int64
 68   maximum_nights                                902210 non-null  int64
 69   calendar_updated                              902210 non-null  object
 70   has_availability                              902210 non-null  object
 71   availability_30                               902210 non-null  int64
 72   availability_60                               902210 non-null  int64
 73   availability_90                               902210 non-null  int64
 74   availability_365                              902210 non-null  int64
 75   calendar_last_scraped                         902210 non-null  object
 76   number_of_reviews                             902210 non-null  int64
 77   first_review                                  477922 non-null  object
 78   last_review                                   477961 non-null  object
 79   review_scores_rating                          454194 non-null  float64
 80   review_scores_accuracy                        453624 non-null  float64
 81   review_scores_cleanliness                     453797 non-null  float64
 82   review_scores_checkin                         453560 non-null  float64
 83   review_scores_communication                   453795 non-null  float64
 84   review_scores_location                        453657 non-null  float64
 85   review_scores_value                           453659 non-null  float64
 86   requires_license                              902210 non-null  object
 87   license                                       43 non-null      object
 88   jurisdiction_names                            0 non-null       float64
 89   instant_bookable                              902210 non-null  object
 90   is_business_travel_ready                      902210 non-null  object
 91   cancellation_policy                           902210 non-null  object
 92   require_guest_profile_picture                 902210 non-null  object
 93   require_guest_phone_verification              902210 non-null  object
 94   calculated_host_listings_count                902210 non-null  int64
 95   reviews_per_month                             477922 non-null  float64
 96   ano                                           902210 non-null  int64
 97   mes                                           902210 non-null  int64
 98   minimum_minimum_nights                        600999 non-null  float64
 99   maximum_minimum_nights                        600999 non-null  float64
 100  minimum_maximum_nights                        600999 non-null  float64
 101  maximum_maximum_nights                        600999 non-null  float64
 102  minimum_nights_avg_ntm                        600999 non-null  float64
 103  maximum_nights_avg_ntm                        600999 non-null  float64
 104  number_of_reviews_ltm                         600999 non-null  float64
 105  calculated_host_listings_count_entire_homes   600999 non-null  float64
 106  calculated_host_listings_count_private_rooms  600999 non-null  float64
 107  calculated_host_listings_count_shared_rooms   600999 non-null  float64
dtypes: float64(31), int64(15), object(62)
memory usage: 743.4+ MB

### 01.3.4. Salvando a tabela unificada

In [11]:
dataset_raw.to_csv(

    consts.DATASET_RAW_PANDAS,

    index = False

)

## 01.4. Compactação dos arquivos

### 01.4.1. Compactando arquivos brutos em csv usando o formato gzip

In [12]:
pd.read_csv(consts.DATASET_RAW_PANDAS, low_memory = False).to_csv(
    
      consts.DATASET_RAW_COMPRESSED_PANDAS,

      index = False,

      compression = 'gzip',
      
)